export const PROFILEIMAGE = "PROFILEIMAGE";
export const PROFILENAME = "PROFILENAME";
export const PROFILEMOBILE = "PROFILEMOBILE";
export const PROFILEID = "PROFILEID";
export const PROFILEADDRESS = "PROFILEADDRESS";
